[general]
# Create Gemini API key: https://aistudio.google.com/app/apikey
GEMINI_API_KEY ="your-api-key-here" 

# Enable YouTube Data API v3: https://console.cloud.google.com/marketplace/product/google/youtube.googleapis.com?q=search&referrer=search
# Get API Key Here: https://console.cloud.google.com/apis/credentials? --> Create Credentials --> API Key
YOUTUBE_API_KEY = "your-api-key-here"  

# Create ElevenLabs account here: https://elevenlabs.io/sign-up 
# Log in and in the lower left corner click on your profile picture -> “Profile + API key”.
ELEVENLABS_API_KEY = "your-api-key-here"